services:
  # Base de datos con PostgreSQL
  db:
    image: postgres:15
    container_name: pacientes_db
    environment:
      POSTGRES_DB: pacientes_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    

  # Backend con Node.js
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: pacientes_backend
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pacientes_db
      DB_USER: admin
      DB_PASSWORD: admin
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend con React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pacientes_frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge